version: '3.8'

services:
  # MySQL Database
  product-mysql:
    image: mysql:latest
    container_name: product-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product_service_db
      MYSQL_USER: product_user
      MYSQL_PASSWORD: product_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_product_data:/var/lib/mysql
      # - ./product-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
  order-mysql:
    image: mysql:latest
    container_name: mysql-order-service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order_service_db
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql
      # - ./order-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  identity-mysql:
    image: mysql:latest
    restart: always
    container_name: identity-service-mysql
    ports:
      - "3309:3306"
    volumes:
      - mysql_identity_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: identity_service_db
      MYSQL_USER: identity_user
      MYSQL_PASSWORD: identity_password
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-mysql:
    image: mysql:latest
    restart: always
    container_name: inventory-service-mysql
    ports:
      - "3310:3306"
    volumes:
      - mysql_inventory_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory_service_db
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_password
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  payment-mysql:
    image: mysql:latest
    restart: always
    container_name: payment-service-mysql
    ports:
      - "3311:3306"
    volumes:
      - mysql_payment_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_service_db
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: payment_password
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5


  # Redis Cache
  redis:
    image: redis:latest
    container_name: shopping-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prometheus (Metrics Collection)
  prometheus:
    image: prom/prometheus:latest
    container_name: ecommerce-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - microservices-network

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./docker/promtail/promtail-docker-config.yml:/etc/promtail/docker-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--config.file=/etc/promtail/docker-config.yml"
    networks:
      - microservices-network

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: "-config.file=/etc/loki/local-config.yaml"
    ports:
      - "3100:3100"
    depends_on:
      - promtail
    networks:
      - microservices-network

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: "-config.file /etc/tempo-config.yml"
    ports:
      - "3200:3200"     # Tempo
      - "9411:9411"     # Zipkin
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo-config.yml
    networks:
      - microservices-network

  # Grafana (Metrics Visualization)
  grafana:
    image: grafana/grafana:latest
    container_name: ecommerce-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - microservices-network
      
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: ecommerce-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: ecommerce-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ecommerce-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  


volumes:
  mysql_product_data:
  mysql_order_data:
  mysql_identity_data:
  mysql_inventory_data:
  mysql_payment_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  microservices-network:
    driver: bridge