global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'online-shopping-monitor'

scrape_configs:
  # Identity Service
  - job_name: 'identity-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['identity-service:8080']
        labels:
          application: 'identity-service'

  # Order Service
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8082']
        labels:
          application: 'order-service'

  # Notification Service
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8083']
        labels:
          application: 'notification-service'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

