global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "api-gateway"

scrape_configs:
  # Spring Boot Application Metrics
  - job_name: "product-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          application: "product-service"
  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "api-gateway"
  - job_name: "identity-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["host.docker.internal:8086"]
        labels:
          application: "identity-service"

  - job_name: "inventory-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["host.docker.internal:8087"]
        labels:
          application: "inventory-service"

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["host.docker.internal:8083"]
        labels:
          application: "notification-service"
  - job_name: "order-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["host.docker.internal:8082"]
        labels:
          application: "order-service"
  - job_name: "payment-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["host.docker.internal:8088"]
        labels:
          application: "payment-service"

  # Prometheus Self-Monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
